import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorials: [
    {
      type: 'category',
      label: 'Tutorials',
      link: {type: 'doc', id: 'tutorials/README'},
      items: [
        'tutorials/getting-started',
        'tutorials/first-app',
        'tutorials/backend-loop',
      ],
    },
  ],
  howTo: [{type: 'autogenerated', dirName: 'how-to'}],
  reference: [{type: 'autogenerated', dirName: 'reference'}],
  explanations: [{type: 'autogenerated', dirName: 'explanations'}],
  plans: [
    {
      type: 'category',
      label: 'Product Plans',
      link: {
        type: 'generated-index',
        title: 'Product Plans',
        slug: '/product/plans',
        description: 'Explore upcoming ideas, generators, and infrastructure plans for the Webstir ecosystem.',
      },
      items: [{type: 'autogenerated', dirName: 'product/plans'}],
    },
  ],
};

export default sidebars;
